# Generated by Django 4.1.4 on 2023-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='measured_at',
            field=models.DateTimeField(),
        ),
    ]
